// Common cultural references and alternate meanings that dictionary APIs miss
module.exports = {
  // Yesterday's puzzle (Dec 14)
  'DUCKLING': 'The Ugly Duckling (fairy tale)',
  'NAPOLEON': 'French emperor; pig in "Animal Farm"; layered pastry',
  'PRINCESS': '"The Little Princess" (book/film)',
  'PIGLET': 'Winnie the Pooh character',
  'EMPEROR': '"The Emperor\'s New Clothes"; Emperor penguin',
  'MERMAID': '"The Little Mermaid" (fairy tale/film)',
  'PORKY': 'Porky Pig (Looney Tunes); British slang "porky pie" = lie',
  'BABE': 'The pig from movie "Babe"; slang for attractive person',
  'COLONEL': 'Homophone of "kernel"',
  'WOULD': 'Homophone of "wood"',
  'FAWN': 'Also: (verb) to flatter or grovel; seek favor through flattery',
  'FLATTER': 'Also: (verb) to praise insincerely; to make look better',
  'CHALK': '"Chalk it up to..." = attribute to; "by a long chalk" = by far',
  'GUSH': 'Also: to praise effusively or excessively',
  'HERCULE': 'Hercule Poirot (detective); HERCULES minus S',
  'POIROT': 'Hercule Poirot (Agatha Christie detective); silent T',
  'PIAZZA': 'Mike Piazza (NY Mets); Italian plaza',
  'SEAVER': 'Tom Seaver (NY Mets pitcher)',
  'GOODEN': 'Dwight Gooden (NY Mets pitcher)',
  'STRAWBERRY': 'Darryl Strawberry (NY Mets); Strawberry Fields',

  // Today's puzzle (Dec 15) - "___ GRAND" theme likely
  'SEE': 'Holy See (Vatican); bishop\'s jurisdiction; "see ya" = goodbye',
  'MONSTER': 'Monster Mash (song); Cookie Monster; energy drink brand',
  'QUARTER': 'No quarter = no mercy; 25-cent coin; football period',
  'ONE HUNDRED': '"Keep it 100" = be real/authentic; 100% = completely',
  'SEMI': 'Semi truck (18-wheeler); semi-final; prefix meaning half',
  'CELSIUS': 'Anders Celsius (Swedish astronomer); metric temperature',
  'BUMPER': 'Bumper sticker; bumper crop = abundant harvest; bumper cars',
  'DUMP': 'Data/memory dump; "take a dump"; dump truck',
  'JOINT': 'Slang for marijuana cigarette; prison; "case the joint"',
  'GIANT': 'NY Giants (NFL/MLB); Jack and the Beanstalk; Andre the Giant',
  'FINAL': 'Final Four (NCAA); Final Fantasy (video games)',
  'HOLE': '"In the hole" = in debt; golf term; Jackson Hole; donut hole',
  'JURY': 'Grand jury; "the jury is still out" = undecided',
  'SLAM': 'Grand Slam (tennis/baseball); poetry slam; slam dunk',
  'PRIX': 'Grand Prix (racing); French for "prize"',
  'PIANO': 'Grand piano; musical dynamics marking (soft)',
};
